// AUTO-GENERATED by scripts/bake-token-meta.ts — brand colors extracted from
// token logos (dominant vibrant hue). Re-run: pnpm bake:colors. Do not edit by hand.

export const BAKED: Record<string, { color: string; ink: string }> = {
  '0xacfe6019ed1a7dc6f7b508c02d1b04ec88cc21bf': { color: '#E23D0B', ink: '#F4F0F4' }, // VVV
  '0x22af33fe49fd1fa80c7149773dde5890d3c76f3b': { color: '#7049EA', ink: '#F4F0F4' }, // BNKR
  '0x9b5e262cf9bb04869ab40b19af91d2dc85761722': { color: '#1D1D1D', ink: '#F4F0F4' }, // NOCK
  '0x6b2504a03ca4d43d0d73776f6ad46dab2f2a4cfd': { color: '#9E6354', ink: '#F4F0F4' }, // REI
  '0x0b3e328455c4059eeb9e3f84b5543f74e24e7e1b': { color: '#A4E1D3', ink: '#34203B' }, // VIRTUAL
  '0xed664536023d8e4b1640c394777d34abaff1df8f': { color: '#5D78E1', ink: '#F4F0F4' }, // POD
  '0x5f980dcfc4c0fa3911554cf5ab288ed0eb13dba3': { color: '#0C0C0B', ink: '#F4F0F4' }, // GITLAWB
  '0xc52aedec3374422d7510e294cfaa90799595cba3': { color: '#326A9C', ink: '#F4F0F4' }, // Surplus
  '0xff8104251e7761163fac3211ef5583fb3f8583d6': { color: '#212527', ink: '#F4F0F4' }, // REPPO
  '0xd080ed3c74a20250a2c9821885203034acd2d5ae': { color: '#8CACD6', ink: '#34203B' }, // ZFI
  '0x7afe438411ee3959c7de6f7fb76bf9c769320ba3': { color: '#56D9CA', ink: '#34203B' }, // BLOCKTRONICS
  '0xbf8e8f0e8866a7052f948c16508644347c57aba3': { color: '#646055', ink: '#F4F0F4' }, // aeon
  '0x9f86db9fc6f7c9408e8fda3ff8ce4e78ac7a6b07': { color: '#D75444', ink: '#F4F0F4' }, // CLAWD
  '0x3722264ab15a1dfce5a5af89e6547f7949a8aba3': { color: '#C7901D', ink: '#F4F0F4' }, // LFI
  '0x4f9fd6be4a90f2620860d680c0d4d5fb53d1a825': { color: '#8D65CC', ink: '#F4F0F4' }, // AIXBT
  '0xf4d97f2da56e8c3098f3a8d538db630a2606a024': { color: '#0457A5', ink: '#F4F0F4' }, // DIEM
  '0x44b28991b167582f18ba0259e0173176ca125505': { color: '#C0D3F6', ink: '#34203B' }, // uPEG
  '0x999b49c0d1612e619a4a4f6280733184da025108': { color: '#A00DB9', ink: '#F4F0F4' }, // SLOP
  '0x829f4b62eebe12af653b4dd4ffc480966f7d7f09': { color: '#141516', ink: '#F4F0F4' }, // sato
  '0xaf1e52927d724fd34773bd53ada57f4c2b742069': { color: '#74481D', ink: '#F4F0F4' }, // SHIT
  '0xbd3ab5859f244cc9f51ee0ca755c5cf663d80040': { color: '#F5B500', ink: '#34203B' }, // PRISM
  '0x6982508145454ce325ddbe47a25d4ec3d2311933': { color: '#429037', ink: '#F4F0F4' }, // PEPE
  '0xe0f63a424a4439cbe457d80e4f4b51ad25b2c56c': { color: '#D8A837', ink: '#34203B' }, // SPX
  '0xf280b16ef293d8e534e370794ef26bf312694126': { color: '#EA9C3C', ink: '#34203B' }, // ASTEROID
  '0xaaee1a9723aadb7afa2810263653a34ba2c21c7a': { color: '#001186', ink: '#F4F0F4' }, // Mog
  '0x8de39b057cc6522230ab19c0205080a8663331ef': { color: '#F2F2F2', ink: '#34203B' }, // wojak
  '0x8ed97a637a790be1feff5e888d43629dc05408f6': { color: '#62CCF5', ink: '#34203B' }, // NPC
  '0x812ba41e071c7b7fa4ebcfb62df5f45f6fa853ee': { color: '#E4AD29', ink: '#34203B' }, // Neiro
  '0x594daad7d77592a2b97b725a7ad59d7e188b5bfa': { color: '#578D30', ink: '#F4F0F4' }, // APU
  '0x68bbed6a47194eff1cf514b50ea91895597fc91e': { color: '#234FA0', ink: '#F4F0F4' }, // ANDY
  '0x26e550ac11b26f78a04489d5f20f24e3559f7dd9': { color: '#814A32', ink: '#F4F0F4' }, // KEKIUS
  '0x28561b8a2360f463011c16b6cc0b0cbef8dbbcad': { color: '#C28F73', ink: '#34203B' }, // MOODENG
  '0x12419a0427c2a27a61c1cb4a49f5fad24fd4e671': { color: '#4A669D', ink: '#F4F0F4' }, // STARMAN
  '0xcab254f1a32343f11ab41fbde90ecb410cde348a': { color: '#729C2E', ink: '#F4F0F4' }, // FROGE
  '0x808507121b80c02388fad14726482e061b8da827': { color: '#163B72', ink: '#F4F0F4' }, // PENDLE
  '0x66761fa41377003622aee3c7675fc7b5c1c2fac5': { color: '#4D64F4', ink: '#F4F0F4' }, // CPOOL
}
